# Generated by Django 4.1.4 on 2022-12-31 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Instructions', models.TextField(max_length=500)),
                ('bodypart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='main_app.bodypart')),
            ],
        ),
    ]
